Search.appendIndex(
    [
                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray",
            "name": "AbstractAssociativeArray",
            "summary": "Abstract\u0020class\u0020for\u0020Associative\u0020Array\u0020\u0028Objectified\u0020Array\u0020Class\u0029",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method___serialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method___unserialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Get\u0020a\u0020count\u0020of\u0020the\u0020elements\u0020of\u0020the\u0020array",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_delete"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Aimplode\u0028\u0029",
            "name": "implode",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_implode"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "Move\u0020back\u0020to\u0020previous\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_prev"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Whether\u0020a\u0020offset\u0020exists",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_offsetExists"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Offset\u0020to\u0020retrieve",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_offsetGet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Offset\u0020to\u0020set",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_offsetSet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Offset\u0020to\u0020unset",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Return\u0020the\u0020current\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_current"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "Move\u0020forward\u0020to\u0020next\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_next"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "Return\u0020the\u0020key\u0020of\u0020the\u0020current\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_key"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "Checks\u0020if\u0020current\u0020position\u0020is\u0020valid",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_valid"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "Rewind\u0020the\u0020Iterator\u0020to\u0020the\u0020first\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_rewind"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_getData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_setData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "Return\u0020an\u0020array\u0020of\u0020keys",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_getKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "Return\u0020an\u0020array\u0020of\u0020values",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_getValues"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AisReadOnly\u0028\u0029",
            "name": "isReadOnly",
            "summary": "Is\u0020this\u0020HashTable\u0020readOnly\u003F",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_isReadOnly"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AlockSize\u0028\u0029",
            "name": "lockSize",
            "summary": "Locks\u0020HashTable\u0020to\u0020current\u0020size",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_lockSize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AisFixedSize\u0028\u0029",
            "name": "isFixedSize",
            "summary": "Determine\u0020if\u0020HashTable\u0020is\u0020of\u0020a\u0020fixed\u0020size",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_isFixedSize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AvalidateKeys\u0028\u0029",
            "name": "validateKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_validateKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003AvalidateKey\u0028\u0029",
            "name": "validateKey",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#method_validateKey"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A\u0024serializeVersion",
            "name": "serializeVersion",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#property_serializeVersion"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A\u0024readOnly",
            "name": "readOnly",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#property_readOnly"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#property_position"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#property_data"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractAssociativeArray\u003A\u003A\u0024fixedSize",
            "name": "fixedSize",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractAssociativeArray.html#property_fixedSize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray",
            "name": "AbstractIndexedArray",
            "summary": "Abstract\u0020class\u0020Collection\u0020\u0028Objectified\u0020Array\u0020Class\u0029",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_prev"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Aimplode\u0028\u0029",
            "name": "implode",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_implode"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "Build\u0020Array\u0020from\u0020data\u0020for\u0020serialization",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method___serialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "Take\u0020Deserialized\u0020Array\u0020and\u0020populate\u0020object\u0020with\u0020that\u0020data",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method___unserialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Whether\u0020a\u0020offset\u0020exists",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_offsetExists"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Offset\u0020to\u0020retrieve",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_offsetGet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Offset\u0020to\u0020set",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_offsetSet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Offset\u0020to\u0020unset",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Return\u0020the\u0020current\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_current"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "Move\u0020forward\u0020to\u0020next\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_next"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "Return\u0020the\u0020key\u0020of\u0020the\u0020current\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_key"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "Checks\u0020if\u0020current\u0020position\u0020is\u0020valid",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_valid"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_rewind"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_getData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_setData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AisStrict\u0028\u0029",
            "name": "isStrict",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_isStrict"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AvalidateKeys\u0028\u0029",
            "name": "validateKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_validateKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AvalidateKey\u0028\u0029",
            "name": "validateKey",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_validateKey"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Amerge\u0028\u0029",
            "name": "merge",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_merge"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_push"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Aintersection\u0028\u0029",
            "name": "intersection",
            "summary": "Find\u0020intersection\u0020of\u0020this\u0020and\u0020another\u0020collection\u0020\u002D\u0020I\u0020would\u0020really\u0020like\u0020to\u0020explore\u0020putting\u0020this\u0020into\u0020the\nCollectionInterface\u0020but\u0020for\u0020now\u0020\u0020it\u0027s\u0020going\u0020to\u0020be\u0020a\u0020non\u002Dcontracted\u0020function.\u0020I\u0020also\u0020REALLY\u0020would\u0020like\u0020to\u0020make\u0020a\nstrict\u0020option\u0020that\u0020allows\u0020for\u0020type\u0020matching.",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_intersection"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Apop\u0028\u0029",
            "name": "pop",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_pop"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "Returns\u0020the\u0020first\u0020element\u0020of\u0020the\u0020collection",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_first"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003AtoRoll\u0028\u0029",
            "name": "toRoll",
            "summary": "Convert\u0020AbstractCollection\u0020to\u0020a\u0020AbstractList\u0020\u0028Roll\u0029",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#method_toRoll"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A\u0024serializeVersion",
            "name": "serializeVersion",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#property_serializeVersion"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A\u0024strict",
            "name": "strict",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#property_strict"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#property_position"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractIndexedArray\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractIndexedArray.html#property_data"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair",
            "name": "AbstractKeyValuePair",
            "summary": "Abstract\u0020class\u0020for\u0020KeyValue\u0020Pair",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_set"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_getKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_getValues"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_rewind"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_valid"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_key"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_next"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "Move\u0020forward\u0020to\u0020previous\u0020element",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_prev"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_current"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Offset\u0020to\u0020set",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_offsetSet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Get\u0020raw\u0020data\u0020in\u0020PHP\u0020Array",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_getData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_setData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_offsetGet"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_offsetExists"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AgetOffsetPosition\u0028\u0029",
            "name": "getOffsetPosition",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_getOffsetPosition"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AvalidateKeys\u0028\u0029",
            "name": "validateKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_validateKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003AvalidateKey\u0028\u0029",
            "name": "validateKey",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method_validateKey"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method___serialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#method___unserialize"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A\u0024serializeVersion",
            "name": "serializeVersion",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#property_serializeVersion"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A\u0024position",
            "name": "position",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#property_position"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#property_keys"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractKeyValuePair\u003A\u003A\u0024values",
            "name": "values",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractKeyValuePair.html#property_values"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractList",
            "name": "AbstractList",
            "summary": "Abstract\u0020class\u0020for\u0020List\u0020\u0028Roll\u0029\u0020Objectified\u0020array\u0020class",
            "url": "classes/PHPAlchemist-Abstracts-AbstractList.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractList\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Offset\u0020to\u0020unset",
            "url": "classes/PHPAlchemist-Abstracts-AbstractList.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractList\u003A\u003Aoffsetset\u0028\u0029",
            "name": "offsetset",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractList.html#method_offsetset"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractList\u003A\u003ArebalanceData\u0028\u0029",
            "name": "rebalanceData",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractList.html#method_rebalanceData"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractList\u003A\u003AisList\u0028\u0029",
            "name": "isList",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractList.html#method_isList"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractNumber",
            "name": "AbstractNumber",
            "summary": "Abstract\u0020Class\u0020for\u0020Number\u0020classes",
            "url": "classes/PHPAlchemist-Abstracts-AbstractNumber.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractNumber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractNumber.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractNumber\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractNumber.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractNumber\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractNumber.html#method___toString"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractNumber\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractNumber.html#property_data"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString",
            "name": "AbstractString",
            "summary": "Abstract\u0020class\u0020for\u0020String",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method___toString"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Get\u0020value\u0020of\u0020String\u0020object0",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_getValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_setValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_contains"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AendsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_endsWith"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_equals"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AhasValue\u0028\u0029",
            "name": "hasValue",
            "summary": "Determine\u0020if\u0020string\u0020has\u0020value",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_hasValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AindexOf\u0028\u0029",
            "name": "indexOf",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_indexOf"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_insert"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AisNullOrEmpty\u0028\u0029",
            "name": "isNullOrEmpty",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_isNullOrEmpty"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AlastIndexOf\u0028\u0029",
            "name": "lastIndexOf",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_lastIndexOf"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_length"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Alower\u0028\u0029",
            "name": "lower",
            "summary": "Convert\u0020string\u0020to\u0020lower\u0020case",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_lower"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003ApadBoth\u0028\u0029",
            "name": "padBoth",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_padBoth"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003ApadLeft\u0028\u0029",
            "name": "padLeft",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_padLeft"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003ApadRight\u0028\u0029",
            "name": "padRight",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_padRight"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_remove"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AsplitOn\u0028\u0029",
            "name": "splitOn",
            "summary": "Convenience\u0020function\u0020for\u0020explode",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_splitOn"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AsplitAt\u0028\u0029",
            "name": "splitAt",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_splitAt"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Aexplode\u0028\u0029",
            "name": "explode",
            "summary": "Explode\u0020to\u0020\u0020CollectionInterface\u0020object",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_explode"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003AstartsWith\u0028\u0029",
            "name": "startsWith",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_startsWith"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Asubstring\u0028\u0029",
            "name": "substring",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_substring"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Aupper\u0028\u0029",
            "name": "upper",
            "summary": "Convert\u0020string\u0020to\u0020UPPER\u0020CASE",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_upper"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003Areplace\u0028\u0029",
            "name": "replace",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#method_replace"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003ABEGINNING_OF_STRING_POSITION",
            "name": "BEGINNING_OF_STRING_POSITION",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#constant_BEGINNING_OF_STRING_POSITION"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts\\AbstractString\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/PHPAlchemist-Abstracts-AbstractString.html#property_value"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface",
            "name": "ArrayInterface",
            "summary": "Parental\u0020Array\u0020Interface",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_valid"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_current"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_key"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_next"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_rewind"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "Move\u0020forward\u0020to\u0020previous\u0020element",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_prev"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_offsetGet"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\ArrayInterface\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-ArrayInterface.html#method_offsetExists"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface",
            "name": "AssociativeArrayInterface",
            "summary": "Array",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_getKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_getValues"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\AssociativeArrayInterface\u003A\u003AisReadOnly\u0028\u0029",
            "name": "isReadOnly",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-AssociativeArrayInterface.html#method_isReadOnly"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface",
            "name": "IndexedArrayInterface",
            "summary": "Parental\u0020Array\u0020Interface",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_setData"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003AisStrict\u0028\u0029",
            "name": "isStrict",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_isStrict"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_push"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Apop\u0028\u0029",
            "name": "pop",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_pop"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\IndexedArrayInterface\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "Returns\u0020the\u0020first\u0020element\u0020of\u0020the\u0020collection",
            "url": "classes/PHPAlchemist-Contracts-IndexedArrayInterface.html#method_first"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface",
            "name": "KeyValuePairInterface",
            "summary": "Key\u0020Value\u0020Pair\u0020Interface",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_current"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_key"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_next"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Aprev\u0028\u0029",
            "name": "prev",
            "summary": "Move\u0020forward\u0020to\u0020previous\u0020element",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_prev"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_valid"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_rewind"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_offsetUnset"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_offsetGet"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_offsetExists"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_setData"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_getData"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_count"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_add"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_set"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_getKeys"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\KeyValuePairInterface\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-KeyValuePairInterface.html#method_getValues"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\NumberInterface",
            "name": "NumberInterface",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-NumberInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface",
            "name": "StringInterface",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method___toString"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_contains"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AendsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_endsWith"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_equals"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Aexplode\u0028\u0029",
            "name": "explode",
            "summary": "Explode\u0020to\u0020\u0020CollectionInterface\u0020object",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_explode"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Get\u0020value\u0020of\u0020String\u0020object0",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_getValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AhasValue\u0028\u0029",
            "name": "hasValue",
            "summary": "Determine\u0020if\u0020string\u0020has\u0020value",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_hasValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AindexOf\u0028\u0029",
            "name": "indexOf",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_indexOf"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_insert"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AisNullOrEmpty\u0028\u0029",
            "name": "isNullOrEmpty",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_isNullOrEmpty"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AlastIndexOf\u0028\u0029",
            "name": "lastIndexOf",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_lastIndexOf"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_length"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003ApadBoth\u0028\u0029",
            "name": "padBoth",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_padBoth"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003ApadLeft\u0028\u0029",
            "name": "padLeft",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_padLeft"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003ApadRight\u0028\u0029",
            "name": "padRight",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_padRight"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_setValue"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003AstartsWith\u0028\u0029",
            "name": "startsWith",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_startsWith"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Asubstring\u0028\u0029",
            "name": "substring",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_substring"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts\\StringInterface\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/PHPAlchemist-Contracts-StringInterface.html#method_remove"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\HashTableFullException",
            "name": "HashTableFullException",
            "summary": "When\u0020a\u0020HashTable\u0020has\u0020reached\u0020the\u0020fixed\u0020limit\u0020and\u0020an\u0020attempt\u0020to\u0020add\u0020data\u0020has\u0020been\u0020made.",
            "url": "classes/PHPAlchemist-Exceptions-HashTableFullException.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\HashTableFullException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-HashTableFullException.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\HashTableFullException\u003A\u003AERROR_UNMATCHED_CLASS",
            "name": "ERROR_UNMATCHED_CLASS",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-HashTableFullException.html#constant_ERROR_UNMATCHED_CLASS"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\InvalidKeyTypeException",
            "name": "InvalidKeyTypeException",
            "summary": "An\u0020invalid\u0020key\u0020has\u0020been\u0020used\u0020for\u0020an\u0020element\u0020in\u0020a\u0020HashTable",
            "url": "classes/PHPAlchemist-Exceptions-InvalidKeyTypeException.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\ReadOnlyDataException",
            "name": "ReadOnlyDataException",
            "summary": "A\u0020HashTable\u0020was\u0020marked\u0020as\u0020read\u002Donly\u0020but\u0020an\u0020attempt\u0020was\u0020made\u0020to\u0020modify\u0020the\u0020HashTable\u0027s\u0020data",
            "url": "classes/PHPAlchemist-Exceptions-ReadOnlyDataException.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedClassException",
            "name": "UnmatchedClassException",
            "summary": "When\u0020a\u0020deserialized\u0020object\u0020doesn\u0027t\u0020match\u0020the\u0020deserializing\u0020class",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedClassException.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedClassException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedClassException.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedClassException\u003A\u003AERROR_UNMATCHED_CLASS",
            "name": "ERROR_UNMATCHED_CLASS",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedClassException.html#constant_ERROR_UNMATCHED_CLASS"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedVersionException",
            "name": "UnmatchedVersionException",
            "summary": "When\u0020a\u0020deserialized\u0020object\u0020doesn\u0027t\u0020match\u0020the\u0020deserializing\u0020version",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedVersionException.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedVersionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedVersionException.html#method___construct"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions\\UnmatchedVersionException\u003A\u003AERROR_WRONG_VERSION",
            "name": "ERROR_WRONG_VERSION",
            "summary": "",
            "url": "classes/PHPAlchemist-Exceptions-UnmatchedVersionException.html#constant_ERROR_WRONG_VERSION"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\ArrayTrait",
            "name": "ArrayTrait",
            "summary": "A\u0020collection\u0020of\u0020usable\u0020array\u0020functions",
            "url": "classes/PHPAlchemist-Traits-ArrayTrait.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\ArrayTrait\u003A\u003AsumByKey\u0028\u0029",
            "name": "sumByKey",
            "summary": "sum\u0020values\u0020in\u0020data\u0020by\u0020key",
            "url": "classes/PHPAlchemist-Traits-ArrayTrait.html#method_sumByKey"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\CLITrait",
            "name": "CLITrait",
            "summary": "Collection\u0020of\u0020usable\u0020CLI\u0020functions",
            "url": "classes/PHPAlchemist-Traits-CLITrait.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\CLITrait\u003A\u003AisCli\u0028\u0029",
            "name": "isCli",
            "summary": "tests\u0020to\u0020see\u0020if\u0020class\u0020is\u0020being\u0020executed\u0020from\u0020command\u0020line",
            "url": "classes/PHPAlchemist-Traits-CLITrait.html#method_isCli"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\GetSetTrait",
            "name": "GetSetTrait",
            "summary": "Trait\u0020that\u0020adds\u0020get\u0028\u0024fieldName\u0029,\u0020set\u0028\u0024fieldName,\u0020\u0024values\u0029,\u0020is\u0028\u0024boolFieldName\u0029",
            "url": "classes/PHPAlchemist-Traits-GetSetTrait.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\GetSetTrait\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Standard\u0020\u0028simple\u0029\u0020getter",
            "url": "classes/PHPAlchemist-Traits-GetSetTrait.html#method_get"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\GetSetTrait\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Standard\u0020\u0028simple\u0029\u0020Setter",
            "url": "classes/PHPAlchemist-Traits-GetSetTrait.html#method_set"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\GetSetTrait\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "Boolean\u0020Getter",
            "url": "classes/PHPAlchemist-Traits-GetSetTrait.html#method_is"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\MagicGetSetTrait",
            "name": "MagicGetSetTrait",
            "summary": "Adds\u0020the\u0020capability\u0020to\u0020have\u0020getters\u0020and\u0020setters\u0020for\u0020class\u0020members\u0020so\u0020that\u0020a\u0020property\u0020on\u0020a\u0020class\u0020such\u0020as\u0020\u0060status\u0060\u0020would\nmagically\u0020gain\u0020\u0060setStatus\u0028\u0024argument\u0029\u0060\u0020and\u0020\u0060getStatus\u0028\u0029\u0060",
            "url": "classes/PHPAlchemist-Traits-MagicGetSetTrait.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\MagicGetSetTrait\u003A\u003A__call\u0028\u0029",
            "name": "__call",
            "summary": "Magic",
            "url": "classes/PHPAlchemist-Traits-MagicGetSetTrait.html#method___call"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\MagicGetSetTrait\u003A\u003AgetMethodVerb\u0028\u0029",
            "name": "getMethodVerb",
            "summary": "Get\u0020the\u0020verb\u0020from\u0020the\u0020method\u0020name\u0020being\u0020called.",
            "url": "classes/PHPAlchemist-Traits-MagicGetSetTrait.html#method_getMethodVerb"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\PerformanceTrait",
            "name": "PerformanceTrait",
            "summary": "",
            "url": "classes/PHPAlchemist-Traits-PerformanceTrait.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits\\PerformanceTrait\u003A\u003AgetPerformance\u0028\u0029",
            "name": "getPerformance",
            "summary": "get\u0020the\u0020performance\u0020data\u0020\u0028Peak\u0020Memory\u0020Usage\u0029\u0020for\u0020a\u0020given\u0020script\u0020or\nclass",
            "url": "classes/PHPAlchemist-Traits-PerformanceTrait.html#method_getPerformance"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Collection",
            "name": "Collection",
            "summary": "Collection\u0020is\u0020a\u0020proper\u0020indexed\u0020Array\u0020class",
            "url": "classes/PHPAlchemist-Types-Collection.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Dictionary",
            "name": "Dictionary",
            "summary": "A\u0020proper\u0020Dictionary\u0020\u0028key\u002Dvalue\u0029\u0020class\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-Dictionary.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Double",
            "name": "Double",
            "summary": "A\u0020Floating\u0020point\u0020Class\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-Double.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\HashTable",
            "name": "HashTable",
            "summary": "A\u0020proper\u0020HashTable\u0020\u0028associative\u0020array\u0029\u0020class\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-HashTable.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Number",
            "name": "Number",
            "summary": "A\u0020integer\u0020class\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-Number.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Roll",
            "name": "Roll",
            "summary": "A\u0020Proper\u0020Generic\u0020List\u0020object\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-Roll.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types\\Twine",
            "name": "Twine",
            "summary": "Twine\u0020is\u0020a\u0020proper\u0020String\u0020class\u0020for\u0020PHP",
            "url": "classes/PHPAlchemist-Types-Twine.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities\\ArrayUtility",
            "name": "ArrayUtility",
            "summary": "",
            "url": "classes/PHPAlchemist-Utilities-ArrayUtility.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities\\ArrayUtility\u003A\u003AisMulti\u0028\u0029",
            "name": "isMulti",
            "summary": "Takes\u0020an\u0020array\u0020test\u0020to\u0020see\u0020if\u0020it\u0020is\u0020multi\u002Ddimensional.",
            "url": "classes/PHPAlchemist-Utilities-ArrayUtility.html#method_isMulti"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities\\ArrayUtility\u003A\u003AsumByKey\u0028\u0029",
            "name": "sumByKey",
            "summary": "sum\u0020values\u0020in\u0020data\u0020by\u0020key",
            "url": "classes/PHPAlchemist-Utilities-ArrayUtility.html#method_sumByKey"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities\\CSVUtil",
            "name": "CSVUtil",
            "summary": "",
            "url": "classes/PHPAlchemist-Utilities-CSVUtil.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities\\CSVUtil\u003A\u003Asputcsv\u0028\u0029",
            "name": "sputcsv",
            "summary": "Nice\u0020String\u0020output\u0020replacement\u0020form\u0020fputcsv\ncode\u0020taken\u0020from\u003A\u0020http\u003A\/\/www.php.net\/manual\/en\/function.fputcsv.php\u002396937",
            "url": "classes/PHPAlchemist-Utilities-CSVUtil.html#method_sputcsv"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Abstracts",
            "name": "Abstracts",
            "summary": "",
            "url": "namespaces/phpalchemist-abstracts.html"
        },                {
            "fqsen": "\\PHPAlchemist",
            "name": "PHPAlchemist",
            "summary": "",
            "url": "namespaces/phpalchemist.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/phpalchemist-contracts.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/phpalchemist-exceptions.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/phpalchemist-traits.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Types",
            "name": "Types",
            "summary": "",
            "url": "namespaces/phpalchemist-types.html"
        },                {
            "fqsen": "\\PHPAlchemist\\Utilities",
            "name": "Utilities",
            "summary": "",
            "url": "namespaces/phpalchemist-utilities.html"
        }            ]
);
